### ISSUE TITLE
Code breaks if betfair add a new field to their models

### ISSUE THREAD

**Issue by ms5** [jmcarp/betfair.py#24]
Recently Betfair added a new field to their model, which appears only to certain market queries. I found out, that in such a case to code will break till the model is adjusted to the new field. 

I understand the logic behind and I think the effort to try to keep the python api in sync with the real Betfair model is the right way to go. Unfortunately it takes sometimes a little while till the model can be fixed and if the code breaks (raises exceptions) during this period the bot is useless for that day.

In an effort to make the code more reliable I came up with a little patch, that does instead of raising an exception on new (unknown) fields, just logs a warning. 

The benefit is see is:
 * if betfair adds new fields: existing code does not break and gives time to fix/adjust to now model

what you guys think about this?

**Comment by jmcarp** [comment]
Thanks for the bug report and fix. Handled by @ms5 in #25.

**Comment by ms5** [comment]
I have to open this bug again, since with the move to schematics the problem is again here. For example I get the following exception on rogue fields and that breaks the data of that market, so my bot is useless again...

```python
schematics.exceptions.ModelConversionError: {'description': {'each_way_divisor': 'Rogue field'}}
```

In general I think, there is no need to raise an exception on rogue fields, because the model/bot will continue to work, even if betfair decides to add new data. this new fields can latter be added to the betfair.py model.
