### ISSUE TITLE
follow up on issue #24, code breaks on rogue fields

### ISSUE THREAD

**Issue by ms5** [jmcarp/betfair.py#41]
I come back to issue #24 , since with the move to schematics the problem is again here. For example I get the following exception on rogue fields and that breaks the data of that market, so my bot is useless again...

```python
schematics.exceptions.ModelConversionError: {'description': {'each_way_divisor': 'Rogue field'}}
```

In general I think, there is no need to raise an exception on rogue fields, because the model/bot will continue to work, even if betfair decides to add new data. this new fields can latter be added to the betfair.py model.

**Comment by jmcarp** [comment]
Thanks for the fix!
