### ISSUE TITLE
Problem running example.

### ISSUE THREAD

**Issue by minimumnz** [jmcarp/betfair.py#50]
I can login, however when run this line:
event_types = client.list_event_types(MarketFilter(text_query='tennis'))

I get this error:
python2.7/site-packages/betfair/utils.py", line 109, in make_payload
    'method': '{base}APING/v1.0/{endpoint}'.format(**locals()),
KeyError: 'endpoint'

**Comment by petedmarsh** [comment]
This was just fixed in #49
